### ISSUE TITLE
On the deployed app, error is thrown when trying to load the swagger schema from non-https servers

### ISSUE THREAD

**Issue by pancho111203** [eclipsesource/jsonforms-swagger#40]
ERROR: zone.js:101 Mixed Content: The page at 'https://jsonforms-swagger.herokuapp.com/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://petstore.swagger.io/v2/swagger.json'. This request has been blocked; the content must be served over HTTPS.

**Comment by hecforga** [comment]
Try to run the deployed editor using this url instead: http://jsonforms-swagger.herokuapp.com/

**Comment by pancho111203** [comment]
@hecforga Works! I'll close this
