### ISSUE TITLE
Heroku build isn't working because of jsonforms dependency

### ISSUE THREAD

**Issue by franciscorubin** [eclipsesource/jsonforms-swagger#43]
When executing "git push heroku master" I am getting the following error, related to the installation of typings on jsonforms. 
I tried to fix it installing typings globally but it doesn't work. 
The problem seems to reside in the way typings is installed on package.json of jsonforms.

remote: -----> Building dependencies
remote:        Installing node modules (package.json)
remote:  
remote:        > jsonforms@1.0.4 postinstall /tmp/build_56a4c9e5afcc2536e652b78dc6ff29bb/node_modules/jsonforms
remote:        > typings install
remote:  
remote:        sh: 1: typings: not found
remote:        - qs@4.0.0 node_modules/express/node_modules/qs
remote:        - statuses@1.2.1 node_modules/send/node_modules/statuses
remote:        - depd@1.1.0 node_modules/serve-static/node_modules/depd
remote:        - statuses@1.2.1 node_modules/serve-static/node_modules/statuses
remote:        - send@0.13.2 node_modules/serve-static/node_modules/send
remote:        angular2-webpack@1.0.0 /tmp/build_56a4c9e5afcc2536e652b78dc6ff29bb
remote:        ├── @angular/router@3.0.0-beta.1
remote:        ├── angular-ui-bootstrap@1.3.3
remote:        ├── core-js@2.4.1
remote:        ├─┬ express@4.14.0
remote:        │ ├─┬ accepts@1.3.3
remote:        │ │ └── negotiator@0.6.1
remote:        │ ├── cookie@0.3.1
remote:        │ ├── encodeurl@1.0.1
remote:        │ ├── finalhandler@0.5.0
remote:        │ ├─┬ proxy-addr@1.1.2
remote:        │ │ └── ipaddr.js@1.1.1
remote:        │ ├── qs@6.2.0
remote:        │ ├── range-parser@1.2.0
remote:        │ ├─┬ send@0.14.1
remote:        │ │ └─┬ http-errors@1.5.0
remote:        │ │   └── setprototypeof@1.0.1
remote:        │ ├── serve-static@1.11.1
remote:        │ └── vary@1.1.0
remote:        ├── lodash@4.14.1
remote:        ├── primeng@1.0.0-beta.11
remote:        ├── primeui@4.1.14
remote:        └── reflect-metadata@0.1.2
remote:  
remote:        npm ERR! Linux 3.13.0-91-generic
remote:        npm ERR! argv "/tmp/build_56a4c9e5afcc2536e652b78dc6ff29bb/.heroku/node/bin/node" "/tmp/build_56a4c9e5afcc2536e652b78dc6ff29bb/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_56a4c9e5afcc2536e652b78dc6ff29bb/.npmrc"
remote:        npm ERR! node v5.11.1
remote:        npm ERR! npm  v3.8.6
remote:        npm ERR! file sh
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno ENOENT
remote:        npm ERR! syscall spawn
remote:  
remote:        npm ERR! jsonforms@1.0.4 postinstall: `typings install`
remote:        npm ERR! spawn ENOENT

**Comment by pancho111203** [comment]
Not necessary anymore, as I changed the host to Firebase.

https://github.com/eclipsesource/jsonforms-swagger/wiki/Deploy-to-Firebase
